### ISSUE TITLE
transport/grpc: dial context affects retrieval of credentials after dial returns

### ISSUE THREAD

**Issue by nhooyr** [googleapis/google-api-go-client#273] opened 2018-06-01 00:21 UTC
```go
package scratch

import (
	"context"
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
	"google.golang.org/api/option"
	gtransport "google.golang.org/api/transport/grpc"
)

func TestMeow(t *testing.T) {
	t.Parallel()

	ctx, cancel := context.WithCancel(context.Background())

	cc, err := gtransport.Dial(ctx, option.WithEndpoint(prodAddr))
	require.NoError(t, err)

	cancel()

	fmt.Println(cc.Invoke(context.Background(), "meow", "meow", "meow"))
}

const prodAddr = "bigtable.googleapis.com:443"
```

will print

```
=== RUN   TestMeow
=== PAUSE TestMeow
=== CONT  TestMeow
rpc error: code = Unauthenticated desc = transport: context canceled
--- PASS: TestMeow (0.25s)
PASS
```

If you remove the cancel() call, all works fine.

Trace of the context from Dial.
1. https://github.com/google/google-api-go-client/blob/f71c6d4abd9757df4168c39856698c341d07251f/transport/grpc/dial.go#L65
1. https://github.com/google/google-api-go-client/blob/f71c6d4abd9757df4168c39856698c341d07251f/internal/creds.go#L41
1. https://github.com/golang/oauth2/blob/ec22f46f877b4505e0117eeaab541714644fdd28/google/default.go#L54-L60
1. https://github.com/golang/oauth2/blob/ec22f46f877b4505e0117eeaab541714644fdd28/google/default.go#L114
1. https://github.com/golang/oauth2/blob/ec22f46f877b4505e0117eeaab541714644fdd28/google/go19.go#L56
1. https://github.com/golang/oauth2/blob/ec22f46f877b4505e0117eeaab541714644fdd28/google/default.go#L90
1. https://github.com/golang/oauth2/blob/ec22f46f877b4505e0117eeaab541714644fdd28/google/google.go#L141
1. https://github.com/golang/oauth2/blob/ec22f46f877b4505e0117eeaab541714644fdd28/oauth2.go#L213
1. https://github.com/golang/oauth2/blob/ec22f46f877b4505e0117eeaab541714644fdd28/oauth2.go#L242

That context passed in on that last file is what is causing this error in particular because it applies for more than just initial retrieval. In fact, it seems like the initial retrieval of credentials or access happens after the Dial returns, as otherwise it would already have the credentials cached and there would be no context cancellation error.

All usage of the context after the call on link 1 should be investigated to ensure its not being held onto longer than the Dial.

**Comment by jba** [comment] 2018-06-01 16:29
Thanks, this is a known issue (if it is an issue): that context is used in a background goroutine that refreshes credentials. We mention it [here](https://godoc.org/cloud.google.com/go):

> Do not attempt to control the initial connection (dialing) of a service by setting a timeout on the context passed to NewClient. Dialing is non-blocking, so timeouts would be ineffective and would only interfere with credential refreshing, which uses the same context.

That's not on this repo, but the `option` and `transport` packages are really intended for use by the packages under `cloud.google.com/go`. 

Anyway, is there something you're trying to accomplish with the cancel? Maybe there's another way.

**Comment by nhooyr** [comment] 2018-06-01 16:37
> Anyway, is there something you're trying to accomplish with the cancel? Maybe there's another way.

Nope, I just add a function written like this:

```go

func openClient(t *testing.T) (*bigtable.Client) {
	const (
		instance = "foo"
		project = "meow"
	)

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*15)
	defer cancel()

	client, err := bigtable.NewClient(ctx, project, instance)
	require.NoError(t, err)
	
	return client
}
```

The issue is that when the client was returned from the function, the context is cancelled and so the background goroutine that refreshes credentials stops working too.

I think it'd make more sense for the background credential refreshing goroutine to take its own context derived from context.Background that is cancelled when the connection is closed.

**Comment by jba** [comment] 2018-06-01 16:48
If you're trying to cancel the gRPC dial, that won't work. The dial happens lazily.

**Comment by nhooyr** [comment] 2018-06-01 16:50
I'm aware of that. I have it there as a safety thing. My issue is that its unexpected and unidiomatic in my opinion for the context passed to NewClient to affect the credential refreshing goroutine which is longer lived than the Dial itself. Furthermore, I can make it blocking by passing in `option.WithGRPCDialOption(grpc.WithBlock())`.

**Comment by jba** [comment] 2018-06-02 17:39
The problem is that there might be values in the context that are relevant for creds. This is going to have to wait until we have a way to detach a context from its timeout/cancellation state.

**Comment by nhooyr** [comment] 2018-06-02 17:40
How about we grab the credentials once before the Dial returns? Then we shouldn't need to use the context again afterwards.

**Comment by nhooyr** [comment] 2018-06-04 15:06
thats fine, but it should not hold onto the dial context.

What I mean is that for the first grab of the credentials before Dial() returns, use the dial context. Thats fine.

But afterwards, we should make the background goroutine use a cancellable context, derived from `context.Background`, which is cancelled when the grpc connection is closed.

This will be more intuitive and more idiomatic with how `context` is supposed to be used.

**Comment by jba** [comment] 2018-06-04 20:21
> But afterwards, we should make the background goroutine use a cancellable context, derived from context.Background, which is cancelled when the grpc connection is closed. I can cook up a PR to make this more concrete.

We can't be sure that there isn't something else in the context that we need. See [my comment above](https://github.com/google/google-api-go-client/issues/273#issuecomment-394104212).

**Comment by nhooyr** [comment] 2018-06-04 23:15
@jba what could be in the context that we need to renew credentials that we have not already gotten on the first time we grabbed credentials?

**Comment by nhooyr** [comment] 2018-06-04 23:19
What could be in the context relevant for crews anyhow?

**Comment by nhooyr** [comment] 2018-06-05 00:06
Argh I see what you mean, there are places in the credentials package where values in the context are grabbed and used. This would become a big breaking change. Not sure if there is a clean non breaking solution.

**Comment by jadekler** [comment] 2019-05-10 17:26
Closing this as the conversation has stalled, and we're planning on re-working some of this area soon. Let me know if you'd like to continue discussing this, though.

**Closed by jadekler** 2019-05-10 17:26 UTC
Labels: type: feature request
