### ISSUE TITLE
Cannot build org_golang_google_api with Bazel rules_go 

### ISSUE THREAD

**Issue by bdhess** [googleapis/google-api-go-client#2175] opened 2023-09-20 14:07 UTC
Relying on this repo via Bazel rules_go seems to be broken right now, unclear if there are any workarounds.

This is needed in order to specify [ClientOption](https://pkg.go.dev/google.golang.org/api/option#ClientOption) values to the Go GAPIC client in code that's built with Bazel.

See also https://github.com/bazelbuild/rules_go/issues/3624

**Comment by quartzmo** [comment] 2023-09-20 22:05
Hi @bdhess,

Thank you for reporting this issue. Can you please provide some more details that isolate or at least suggest where the defect might be in this repo? Per your link to https://github.com/bazelbuild/rules_go/issues/3624, it appears to me that the problem is in the rules_go and/or gazelle tooling. Forgive me if I'm missing something. Maybe with some more details I will better understand what can be fixed in google-api-go-client.

**Comment by quartzmo** [comment] 2023-09-25 15:12
Closing now due to lack of info. Please reopen if you can demonstrate where a defect might be in this repo.

**Closed by quartzmo** 2023-09-25 15:12 UTC
Labels: type: question, needs more info

**Comment by bdhess** [comment] 2023-09-25 17:15
I am confused.  Is it the case that Google's official Go clients do not support being built with Bazel?

**Comment by quartzmo** [comment] 2023-09-25 17:40
My understanding is that this repo supports standard Go tooling. @codyoss Can you comment on this?

**Comment by codyoss** [comment] 2023-09-25 18:21
> I am confused. Is it the case that Google's official Go clients do not support being built with Bazel?

We do not test building with Bazel, although through gazelle, rules_go, and ecosystem our libraries should be able to be built with the tooling. But since this does not cause issues in standard Go tooling, this leads me to believe the issue is likely a misconfiguration and/or an issue in gazelle. We do not provide workspace files for bazel so everything comes from the magic of gazelle synthesizing and bazelifiying the repo.

**Comment by quartzmo** [comment] 2023-09-26 23:36
@bdhess Can you link/explain anything here for external users?

**Comment by bdhess** [comment] 2023-09-27 03:49
Yes - added at https://github.com/bazelbuild/rules_go/issues/3624#issuecomment-1735592455
