### ISSUE TITLE
Bazel project broken after upgrade to v0.117.0

### ISSUE THREAD

**Issue by ankurcha** [googleapis/google-api-go-client#1946] opened 2023-04-14 04:57 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: golang
  - OS: linux
  - Language runtime version: 1.20.3
  - Package version: 0.117.0

#### Steps to reproduce

  1. Create a bazel golang project with gazelle + dependency on `google.golang.org/api@v0.116.0`
  2. Run `go mod tidy && go mod vendor`
  3. Generate bazel build files using `bazel run //:gazelle`.
  4. Run `bazel build //...` (Passes)
  5. Run `go build ./...`  (Passes)
  6. Update dependency `go get -u google.golang.org/api@v0.117.0`
  7. Run `go mod tidy && go mod vendor`
  8. Generate bazel build files using `bazel run //:gazelle`.
  9. Run `bazel build //...` (Fails)
  10. Run `go build ./...` (Passes)

Error produced 

```
ERROR: /home/project_name/vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/BUILD:23:11: no such package 'internal/v2/tlsconfigstore/example_cert_key': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/project_name/internal/v2/tlsconfigstore/example_cert_key and referenced by '//vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore:tlsconfigstore'
ERROR: Analysis of target '//apps/cell_manager/cmd:cmd' failed; build aborted: no such package 'internal/v2/tlsconfigstore/example_cert_key': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/project_name/internal/v2/tlsconfigstore/example_cert_key
INFO: Elapsed time: 0.355s
I
```

Thanks!

**Comment by noahdietz** [comment] 2023-04-14 17:26
I'm not sure how much we can help you here as the issue sounds like it is related to how `gazelle` is resolving Go dependencies (and generating `BUILD` files for them on the fly). The code/dependency added between the releases is entirely valid Go code and builds normally with Go tooling. I suggest you open an issue in the [gazelle repo](https://github.com/bazelbuild/bazel-gazelle/issues).

That said, here are some things to try:
* Ensure that your `vendor` directory contains the transitive dependency for `s2a-go`
*  try removing the `vendor` between updates
* Have you tried you running `gazelle` with the `-external vendored` [flag](https://github.com/bazelbuild/bazel-gazelle#dependency-resolution)? 
* Have you run `bazel clean --expunge` between builds (caching can play an issue sometimes)?

I'm going to close this, but if further debugging with the gazelle folks turns up a concrete issue with adding the dependency that was added for 117, then please return and we can reopen this.

**Closed by noahdietz** 2023-04-14 17:26 UTC
Labels: type: question

**Comment by noahdietz** [comment] 2023-04-18 19:40
Looks like the issue is reported here: https://github.com/google/s2a-go/issues/102 Follow that for a solution (at some point).

**Comment by noahdietz** [comment] 2023-04-19 23:26
This was fixed upstream in `s2a-go` and the updated dependency has been added in the v0.119.0 release of this module.
