### ISSUE TITLE
json: cannot unmarshal array into Go value of type admob.GenerateNetworkReportResponse

### ISSUE THREAD

**Issue by gif-gif** [googleapis/google-api-go-client#2846] opened 2024-10-29 12:09 UTC
```
	res, err := c.AdmobService.Accounts.NetworkReport.Generate("accounts/pub-2200607303212623", &admob.GenerateNetworkReportRequest{
		ReportSpec: &admob.NetworkReportSpec{
			DateRange: &admob.DateRange{
				EndDate: &admob.Date{
					Day:   21,
					Month: 8,
					Year:  2021,
				},
				StartDate: &admob.Date{
					Day:   20,
					Month: 8,
					Year:  2021,
				},
			},
			Dimensions:    []string{"DATE", "APP", "COUNTRY"},
			MaxReportRows: 100000,
			Metrics:       []string{"CLICKS", "ESTIMATED_EARNINGS"},
		},
	}).Do()
```
error: json: cannot unmarshal array into Go value of type admob.GenerateNetworkReportResponse
Haven't you solved this problem yet? 
I used the latest code repository but it still got an error

**Comment by codyoss** [comment] 2024-10-29 14:10
This appears to be a dupe of #1182

**Closed** 2024-10-31 08:36 UTC
Labels: priority: p2, type: bug
