### ISSUE TITLE
PurchasesSubscriptionsService return 401 permissionDenied

### ISSUE THREAD

**Issue by richzw** [googleapis/google-api-go-client#327] opened 2019-01-09 09:35 UTC
There was one google console project account linked to Google Play account, and there are several apps under this Google Play account. And the `PurchasesSubscriptionsService.Get` could work well before. 

Unfortunately, this google console project account was **unlinked**/**deleted** to Google Play account by mistake. We try to solve this issue through re-linked this google console project account to Google Play account again.

As a result, server could invoke `PurchasesSubscriptionsService.Get` successfully for most of apps, except one app return `401: The current user has insufficient permissions to perform the requested operation., permissionDenied`.

That case confuse us why only one app could **NOT** call `PurchasesSubscriptionsService.Get`? Could someone help us?

**Comment by richzw** [comment] 2019-01-09 09:40
We have tried to add another one new google console project account to Google Play account, it failed to call `PurchasesSubscriptionsService.Get` either and return the same error.

**Comment by richzw** [comment] 2019-01-10 03:20
Wow, after about 24 hours, it become work automatically. Is there any delay of that? @jadekler

**Comment by jadekler** [comment] 2019-01-10 18:07
That is very strange. I'm not sure what the cause could be. Will try to find time to investigate.

**Comment by fefine** [comment] 2019-03-13 09:30
I met the same error, this is my code:
````
type Client struct {
	httpCli *http.Client
}

func NewClient(jsonPath string) (*Client, error) {

	bs, err := ioutil.ReadFile(jsonPath)
	if err != nil {
		return nil, fmt.Errorf("failed to open android service account json; err: %v", err)
	}

	ctx := context.WithValue(context.Background(), oauth2.HTTPClient, &http.Client{Timeout: 10 * time.Second})

	conf, err := google.JWTConfigFromJSON(bs, androidpublisher.AndroidpublisherScope)
	if err != nil {
		return nil, fmt.Errorf("failed to create android validator client; err: %v", err)
	}
	return &Client{conf.Client(ctx)}, nil
}


func (c *Client) VerifyProduct(
	ctx context.Context,
	packageName string,
	productID string,
	token string,
) (*androidpublisher.ProductPurchase, error) {
	service, err := androidpublisher.New(c.httpCli)
	if err != nil {
		return nil, err
	}

	ps := androidpublisher.NewPurchasesProductsService(service)
	result, err := ps.Get(packageName, productID, token).Context(ctx).Do()

	return result, err
}
````

Where is the problem?

**Comment by fefine** [comment] 2019-03-13 15:23
I got the answer form [here](https://github.com/googleapis/google-api-nodejs-client/issues/1382#issuecomment-466306678) @richzw @jadekler

**Comment by jadekler** [comment] 2019-03-13 16:04
Good to know. That's news to me which I'll be sure to propagate next time this issue comes up. Thanks for following up here.

Now that we understand the problem, are y'all OK with me closing this issue?

**Comment by jadekler** [comment] 2019-04-12 18:52
Closing the issue.

**Closed by jadekler** 2019-04-12 18:52 UTC
Labels: needs more info, type: question
