### ISSUE TITLE
YouTube Data API: Videos.insert drops selfDeclaredMadeForKids because it is omitempty

### ISSUE THREAD

**Issue by wesleym** [googleapis/google-api-go-client#1778] opened 2022-12-09 20:23 UTC
# Repro case

**Minimal example:** https://github.com/wesleym/symmetrical-goggles

The code builds up a `Videos.insert` call but doesn't actually try to upload a YouTube video. However, the buggy behaviour is also observed with a real upload.

**Expected:** The JSON-marshalled request object printed to the screen contains the field `status`. That object contains the field `selfDeclaredMadeForKids` set to the boolean value `false`.

**Actual:** `{"snippet":{"categoryId":"1","title":"Test Video"},"status":{}}`

# Additional notes

This appears to happen because selfDeclaredMadeForKids has `omitempty` in its struct tag. Suspected code location:

https://github.com/googleapis/google-api-go-client/blob/6193507246bdb77dfc431d552c3c88585de314fe/youtube/v3/youtube-gen.go#L10145

This also affects `Videos.update`, another method that accepts `videos` resources. This issue also may affect the other `selfDeclaredMadeForKids` fields.

Defaulting this value to false seems dangerous, since such a value affirmatively answers, "I declare this video not to be made for kids."

# Background

The [YouTube Data API](ytapi) allows a user to upload a video using the [`Videos.insert` method](ytins). This operation uploads to YouTube both a binary video file and YouTube video metadata in the form of a [`videos` resource](ytvid).

One of the fields in the `videos` resource is [`status.selfDeclaredMadeForKids`](yt4kids). This field allows an uploader to answer the question of whether a video is *made for kids*. The *made for kids* status must be set in the API or in YouTube Studio. To set this status at upload time, this field must be present and be `false`. This field being absent will neither mark the video as *made for kids* nor not *made for kids*.

Because this field isn't being set from requests from the Go API client library, the result is a "successfully" uploaded video that is silently blocked from views until the *made for kids* setting is set in YouTube Studio.

# Environment

```
PS C:\Users\Wesley\Source\symmetrical-goggles> go version
go version go1.19.4 windows/amd64
```

```
require google.golang.org/api v0.104.0
```

```
PS C:\Users\Wesley\Source\symmetrical-goggles> systeminfo

...
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19044 N/A Build 19044
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
...
```

[ytapi]: https://developers.google.com/youtube/v3
[ytins]: https://developers.google.com/youtube/v3/docs/videos/insert
[ytvid]: https://developers.google.com/youtube/v3/docs/videos#resource-representation
[yt4kids]: https://developers.google.com/youtube/v3/docs/videos#status.selfDeclaredMadeForKids

**Comment by quartzmo** [comment] 2022-12-09 22:25
Hi @wesleym,

This issue is essentially a duplicate of #938.

Please see docs on [ForceSendFields](https://pkg.go.dev/google.golang.org/api#hdr-ForceSendFields), summarized here:

> You can override the `omitempty` feature by adding the field name to the `ForceSendFields` slice. See `ForceSendFields` docs on any struct for more details. ([VideoStatus](https://github.com/googleapis/google-api-go-client/blob/6193507246bdb77dfc431d552c3c88585de314fe/youtube/v3/youtube-gen.go#L10157-L10163) for example):

```go
// ForceSendFields is a list of field names (e.g. "Addresses") to
// unconditionally include in API requests. By default, fields with
// empty or default values are omitted from API requests. However, any
// non-pointer, non-interface field appearing in ForceSendFields will be
// sent to the server regardless of whether the field is empty or not.
// This may be used to include empty fields in Patch requests.
ForceSendFields [][string](https://pkg.go.dev/builtin#string) `json:"-"`
```

1. The `false` default value for `` is the decision of the API product owner.
2. `omitempty` is broadly used for all JSON-mapped structs in the client libraries in this repo.
3. The solution to your problem is to

**Closed by quartzmo** 2022-12-09 22:25 UTC
Labels: priority: p2, type: bug

**Comment by wesleym** [comment] 2022-12-11 03:57
I tried adding ForceSendFields, and it does exactly what I need. Apologies for the dupe and thanks for your help!
