### ISSUE TITLE
Error 401: Request had invalid authentication credentials but working with python library

### ISSUE THREAD

**Issue by uditsrn28** [googleapis/google-api-go-client#1502] opened 2022-04-05 09:13 UTC
#### Environment details

  - Programming language: Golang
  - OS: MacOS
  - Language runtime version: 1.18
  - Package version: .72

#### Steps to reproduce

  1. Used the sample code - https://developers.google.com/sheets/api/quickstart/go#step_3_run_the_sample
  2. Used the credential and token file from my account.
  3. Execute the file
  

Got this error
`googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.\nMore details:\nReason: authError, Message: Invalid Credentials\n`

The same credentials are working with python library. 
Thanks!

**Comment by uditsrn28** [comment] 2022-04-05 17:46
When I pass the access_token to oauth2.Token{} it fails, If I don't pass access_token it works like a charm.

**Comment by codyoss** [comment] 2022-04-05 18:47
I am unable to reproduce this issues. I used the code you linked to, did a browser redirect and I copied the code found in the URL of the redirect back to the application. Then is printed as it should.

**Comment by codyoss** [comment] 2022-04-05 18:58
This example does not due it but you could start a server up locally to and read back the code from the redirect so you don't have to due it by hand. Closing this issue for now though since running the code as is /w a Desktop credential seems to just work with a current version of the API.

**Closed by codyoss** 2022-04-05 18:58 UTC
Labels: priority: p2, type: bug
