### ISSUE TITLE
Cannot deploy Cloud Run using API: badRequest INVALID_ARGUMENT (no further details provided)

### ISSUE THREAD

**Issue by tommed** [googleapis/google-api-go-client#436] opened 2019-12-18 17:00 UTC
## Client

Run-v1: `google.golang.org/api/run/v1`

## Describe Your Environment

* JetBrains GoLand IDE
* go 1.13.4
* `google.golang.org/api v0.15.0` (have also tried with `google.golang.org/api v0.14.0`, same result)
* Google Cloud Run

## Expected Behavior

Ability to deploy a new Cloud Run Service object using the golang library.

## Actual Behavior

Attempting to deploy a new Cloud Run service returns a `badRequest` response, with status `INVALID_ARGUMENT` despite basing the Service model on an existing, manually created service using:

 `gcloud run services describe existing-service1 --format=json --project=MY_PROJECT --platform=managed`

*** [Click here for the code used to attempt the deployment](https://gist.github.com/tommed/63f4740402ecc95e794963285f2e6042#file-gcp_cloudrun-go-L73) ***

Error:

```json
{
  "error": {
    "code": 400,
    "message": "The request has errors",
    "errors": [
      {
        "message": "The request has errors",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

Happy to supply any further info if needed?

**Comment by jadekler** [comment] 2019-12-19 16:13
Hello! This appears to be an issue about the cloud run API rather than the auto-generated library for cloud run. The cloud run team does not monitor this (auto-generator specific) issue tracker - would you mind using one of the support channels listed on their product page? https://cloud.google.com/run/docs/support

Closing for now, but happy to continue the conversation.

**Comment by tommed** [comment] 2019-12-20 09:24
Thanks, have done. Link for reference:

https://issuetracker.google.com/issues/146592591

**Comment by tj** [comment] 2020-06-13 09:17
Was this ever resolved? I see the same error, and I don't seem to be doing anything wrong from what I can tell, in any case the error is pretty vague

```go
parent := fmt.Sprintf("namespaces/%s", m.ProjectID)

client, err := run.NewService(ctx)
if err != nil {
	return fmt.Errorf("creating client: %w", err)
}

res, err := client.Namespaces.Services.Create(parent, &run.Service{
	ApiVersion: "serving.knative.dev/v1",
	Kind:       "Service",
	Metadata: &run.ObjectMeta{
		Name: "apex-logs",
		Labels: map[string]string{
			"cloud.googleapis.com/location": m.Region,
		},
	},
	Spec: &run.ServiceSpec{
		Template: &run.RevisionTemplate{
			Metadata: &run.ObjectMeta{
				Annotations: map[string]string{
					"autoscaling.knative.dev/maxScale":  "100",
				},
			},
			Spec: &run.RevisionSpec{
				TimeoutSeconds:       900, // TODO: decide on timeout
				ContainerConcurrency: 80,
				Containers: []*run.Container{
					{
						Image: serverContainerImage,
						Resources: &run.ResourceRequirements{
							Limits: map[string]string{
								"cpu":    "1",
								"memory": "128Mi",
							},
						},
					},
				},
			},
		},
	},
}).Do()
```

**Comment by steren** [comment] 2020-06-17 04:02
The Cloud Run API team will work on returning a better error message. 

But I suggest we re-open this issue @jadekler 

Users of the API are able to deploy to Cloud Run without issues (see [this post](https://ahmet.im/blog/gcloud-run-deploy/) which is using a hand written Go client for example)

The actual issue is very likely due to this library, which I guess does not generate the expected payload.

CC @JustinBeckwith

**Comment by steren** [comment] 2020-06-17 04:06
in the [JSON object](https://github.com/googleapis/google-api-go-client/issues/436#issuecomment-567133982) reported above: I see that `spec.template.name` is set to `test1`. This is likely the culprit, because I think the revision name must be prefixed by the service name. Can you try leaving this field unset, or use `test1-foo` ?

**Comment by steren** [comment] 2020-06-17 04:14
This is also confirmed by manually deploying the [payload reported above](https://github.com/googleapis/google-api-go-client/issues/436#issuecomment-567133982), we get this error message:
> The revision name must be prefixed by the name of the enclosing Service or Configuration with a trailing -

**Comment by steren** [comment] 2020-06-17 20:55
Note that we expect error messages to now be better propagated thanks to https://github.com/googleapis/google-api-go-client/commit/4554f64b6b0b7213cbe6bf75678cacc28ed28a03

What release of the client library are you using?

If the latest is still not propagating the error message, then we have more work to do.

**Comment by tj** [comment] 2020-06-18 09:43
ahhh weird I was v0.26.0, for some reason Go didn't fetch the latest, but it looks like v0.27.0 also responds with ` Error 400: The request has errors, badRequest` and no additional details

**Comment by codyoss** [comment] 2020-06-22 23:18
I will look more into why the error message is not making back to the client. @tj Would you mind trying the following: `client, err := run.NewService(ctx, option.WithEndpoint("https://europe-west1-run.googleapis.com/"))`. The API you are trying to call requires using a regional endpoint I believe.

**Comment by codyoss** [comment] 2020-06-22 23:35
I double checked the error being returned from the service in this instance and there is indeed no extra details. All the information known is being returned to the client.

**Comment by tj** [comment] 2020-06-23 13:52
Oh wow, looks like it works now thanks a lot @codyoss! Sorry about that, I'm pretty new to GCP maybe, but that explains why it's returning a pretty generic error. I guess the only actionable thing would be to return an error specific to the endpoint being invalid

**Comment by codyoss** [comment] 2020-06-23 13:55
Glad it worked. I am going to re-close this issue as the only action item sounds like returning some better error messages from the server and that will be tracked internally.

**Closed by codyoss** 2020-06-23 13:55 UTC
Labels: type: question

**Comment by steren** [comment] 2020-06-23 21:29
It seems that the Go library still struggles to surface error messages, see my comment in https://github.com/googleapis/google-api-go-client/issues/436#issuecomment-645619987

**Comment by codyoss** [comment] 2020-06-23 21:34
@steren I checked the raw response as mentioned in https://github.com/googleapis/google-api-go-client/issues/436#issuecomment-647821435 and there are no extra details included in the error that I saw. Were you expecting more details to be returned to the client?

**Comment by aaron-lerner** [comment] 2020-06-23 23:51
I see the server returning more details to the client. Here's an example with curl:
```
$ curl \
-d '{"apiVersion": "serving.knative.dev/v1", "kind": "Service", "metadata": {"name": "new-service", "namespace": "$PROJECT_ID"}, "spec": {"template": {"spec": {"containers": [{"image": "gcr.io/cloudrun/hello"}]}}}}' \
-H 'Authorization: Bearer $TOKEN' \
-H 'Content-Type: application/json' \
https://run.googleapis.com/apis/serving.knative.dev/v1/namespaces/$PROJECT_ID/services
```
Returns:
```
{
  "error": {
    "code": 400,
    "message": "The request has errors",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "region",
            "description": "No region provided in host name, in resource name/parent, or in the request."
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.DebugInfo",
        "detail": "[ORIGINAL ERROR] generic::invalid_argument: userFacingMessage: The request has errors; userFacingDetails: field_violations {\n  field: \"region\"\n  description: \"No region provided in host name, in resource name/parent, or in the request.\"\n}\n; \ncom.google.cloud.eventprocessing.manager.api.error.MalformedRequestException: userFacingMessage: The request has errors; userFacingDetails: field_violations {\n  field: \"region\"\n  description: \"No region provided in host name, in resource name/parent, or in the request.\"\n}\n;  Code: INVALID_ARGUMENT [google.rpc.error_details_ext] { message: \"The request has errors\" details { type_url: \"type.googleapis.com/google.rpc.BadRequest\" value: \"\\nV\\n\\006region\\022LNo region provided in host name, in resource name/parent, or in the request.\" } }"
      }
    ]
  }
}
```
Is the go library definitely handling these error responses properly? All INVALID_ARGUMENTS are returned in a similar manner by Cloud Run. Using the test case added in https://github.com/googleapis/google-api-go-client/commit/4554f64b6b0b7213cbe6bf75678cacc28ed28a03 as an example, it can be triggered with a request to a regional endpoint like:
```
$ curl \
-d '{"apiVersion": "serving.knative.dev/v1", "kind": "Service", "metadata": {"name": "new-service", "namespace": "$PROJECT_ID"}, "spec": {"template": {"metadata": {"name": "rev-00001"}, "spec": {"containers": [{"image": "gcr.io/cloudrun/hello"}]}}}}' \
-H 'Authorization: Bearer $TOKEN' \
-H 'Content-Type: application/json' \
https://us-central1-run.googleapis.com/apis/serving.knative.dev/v1/namespaces/$PROJECT_ID/services
```
Which returns a response:
```
{
  "error": {
    "code": 400,
    "message": "The request has errors",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "metadata.name",
            "description": "The revision name must be prefixed by the name of the enclosing Service or Configuration with a trailing -"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.DebugInfo",
        "detail": "[ORIGINAL ERROR] generic::invalid_argument: userFacingMessage: The request has errors; userFacingDetails: field_violations {\n  field: \"metadata.name\"\n  description: \"The revision name must be prefixed by the name of the enclosing Service or Configuration with a trailing -\"\n}\n; \ncom.google.cloud.eventprocessing.manager.api.error.MalformedRequestException: userFacingMessage: The request has errors; userFacingDetails: field_violations {\n  field: \"metadata.name\"\n  description: \"The revision name must be prefixed by the name of the enclosing Service or Configuration with a trailing -\"\n}\n;  Code: INVALID_ARGUMENT [google.rpc.error_details_ext] { message: \"The request has errors\" details { type_url: \"type.googleapis.com/google.rpc.BadRequest\" value: \"\\n{\\n\\rmetadata.name\\022jThe revision name must be prefixed by the name of the enclosing Service or Configuration with a trailing -\" } }"
      }
    ]
  }
}
```

**Comment by codyoss** [comment] 2020-06-24 02:29
@aaron-lerner The only difference between the requests you are making and the Go Client makes are the headers.

Exploring this I decided to selectively remove some of the headers from the Go Client requests. If I remove the user agent header I get the following:

```json
{
  "error": {
    "code": 400,
    "message": "The request has errors",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "region",
            "description": "No region provided in host name, in resource name/parent, or in the request."
          }
        ]
      }
    ]
  }
}
```
This returns the following error to the client in this case.

```
2020/06/23 20:12:53 googleapi: Error 400: The request has errors
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "No region provided in host name, in resource name/parent, or in the request.",
        "field": "region"
      }
    ]
  }
]
```

When I add the user-agent back in:

```json
{
  "error": {
    "code": 400,
    "message": "The request has errors",
    "errors": [
      {
        "message": "The request has errors",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

Which results in the following error in the client:

```
googleapi: Error 400: The request has errors, badRequest
```

Here is the header: `"User-Agent": "google-api-go-client/0.5"`

It looks like the backend sends back different errors if this header is present. This can also be reproduced with the curl command you provided, if you add the header:

```
$ curl \
-d '{"apiVersion": "serving.knative.dev/v1", "kind": "Service", "metadata": {"name": "new-service", "namespace": "$PROJECT_ID"}, "spec": {"template": {"metadata": {"name": "rev-00001"}, "spec": {"containers": [{"image": "gcr.io/cloudrun/hello"}]}}}}' \
-H 'Authorization: Bearer $TOKEN' \
-H 'Content-Type: application/json' \
-H 'User-Agent: google-api-go-client/0.5' \
https://us-central1-run.googleapis.com/apis/serving.knative.dev/v1/namespaces/$PROJECT_ID/services
```

**Comment by steren** [comment] 2020-06-24 21:14
Wow, that was not expected. Thanks for catching that.

We'll track this internally and remove this special behavior (internal issue: 159834830)

**Comment by rcmarini** [comment] 2020-07-12 05:50
> in the [JSON object](https://github.com/googleapis/google-api-go-client/issues/436#issuecomment-567133982) reported above: I see that `spec.template.name` is set to `test1`. This is likely the culprit, because I think the revision name must be prefixed by the service name and `-`. Can you try leaving this field unset, or use `test1-foo` ?

Thank you very much @steren. This comment was help me a lot.
