### ISSUE TITLE
grpc.RoundRobin and grpc.WithBalancer no longer exist

### ISSUE THREAD

**Issue by jqll** [googleapis/google-api-go-client#441] opened 2020-01-10 22:43 UTC
We are using this library and seeing these errors:

../google.golang.org/api/option/option.go:153:14: undefined: grpc.RoundRobin
../google.golang.org/api/option/option.go:154:42: undefined: grpc.WithBalancer

Sounds like gRPC removed these legacy APIs: https://github.com/grpc/grpc-go/commit/336cf8d76145dc5ebd517fd9c19e14c6822450b3

**Comment by menghanl** [comment] 2020-01-10 23:07
gRPC is pined at version v1.20.1, so this shouldn't break until the version is bumped:
https://github.com/googleapis/google-api-go-client/blob/64f53cc407027fc5c680faf0e33aae2a6bbdf18f/go.mod#L21

**Comment by nolanmar511** [comment] 2020-01-10 23:12
We're not yet using go modules in the test cases which we saw this failure with, so that might explain why pinning within google-api-go-client/go.mod didn't have an effect for our use case.

Is it expected, then, that this change will break users who aren't using go modules?

**Comment by dfawley** [comment] 2020-01-10 23:50
This change will break users who are using go modules as well due to MVS.

Unfortunately, these APIs must be removed.  They were marked as experimental since v1.0 and have been marked with deprecation tags for 6 months.  Removing them is allowed under the [grpc-go versioning policy](https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md).

**Comment by nolanmar511** [comment] 2020-01-11 00:07
@menghanl -- Is it possible to confirm (or check) that using go modules will fix this issue? If so, is that our only work-around. 

I'm a bit hesitant to attempt to adopt go modules right now if it won't necessarily provide a fix.

**Comment by dfawley** [comment] 2020-01-11 00:57
If you use go modules in your own project, you _can_ pin a specific version, which would work:

https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

Alternatively, you could vendor grpc at an older version.

**Comment by nolanmar511** [comment] 2020-01-12 08:31
Thanks. I'll work on switching to using go modules. Perhaps my team missed some sign that this was coming, but it's been a difficult surprise for us.

Since it seems like this library now exclusively supports users who also use go modules, it would be nice to see that mentioned on the README.md for this repo. If it's documented somewhere else, a pointer to that documentation would be great.

**Comment by max202021** [comment] 2020-01-12 16:50
Any updated on this? it is blocking production google cloud build

**Comment by zdenham** [comment] 2020-01-12 18:26
I am currently using go modules in my project, and have tried using the replace directive, but still getting the above error.

@dfawley am I missing something here?

```
replace google.golang.org/grpc => google.golang.org/grpc v1.15.0
```

**Comment by cosmin8905** [comment] 2020-01-13 16:02
Update: 
The issue still appears to be happening:


go get -u google.golang.org/api/option
# google.golang.org/api/option
/Users/cosmin/go/src/google.golang.org/api/option/option.go:153:14: undefined: grpc.RoundRobin
/Users/cosmin/go/src/google.golang.org/api/option/option.go:154:42: undefined: grpc.WithBalancer

**Comment by stapelberg** [comment] 2020-01-13 17:05
FYI: to pin gRPC to the latest released version (before the symbols were removed), use:

```
go mod edit -replace google.golang.org/grpc=google.golang.org/grpc@v1.26.0
```

**Comment by dfawley** [comment] 2020-01-13 17:07
> FYI: to pin gRPC to the latest released version (before the symbols were removed), use:

NOTE: this will only work on a top-level `go.mod` file, i.e. the one that contains the go binary you are building.  It does not work in a library's `go.mod`, so it could not be applied in this repo.

**Comment by dfawley** [comment] 2020-01-13 17:08
Sent #442 to remove the usages of the experimental gRPC API.  Anyone depending on this experimental APIs will be broken, but users not depending on them will be unbroken.

**Comment by Niek-Okido** [comment] 2020-01-13 17:32
i made line 153 and 154 as command that is the one that causing the issue :
this is not perfect but when you are sure you are not using this function will be no problem  so replace the : \go\src\google.golang.org\api\option\option.go with the the text below

kind regards Niek Tuytel

`// Copyright 2017 Google LLC.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package option contains options for Google API clients.
package option

import (
	"net/http"

	"golang.org/x/oauth2"
	"google.golang.org/api/internal"
	"google.golang.org/grpc"
)

// A ClientOption is an option for a Google API client.
type ClientOption interface {
	Apply(*internal.DialSettings)
}

// WithTokenSource returns a ClientOption that specifies an OAuth2 token
// source to be used as the basis for authentication.
func WithTokenSource(s oauth2.TokenSource) ClientOption {
	return withTokenSource{s}
}

type withTokenSource struct{ ts oauth2.TokenSource }

func (w withTokenSource) Apply(o *internal.DialSettings) {
	o.TokenSource = w.ts
}

type withCredFile string

func (w withCredFile) Apply(o *internal.DialSettings) {
	o.CredentialsFile = string(w)
}

// WithCredentialsFile returns a ClientOption that authenticates
// API calls with the given service account or refresh token JSON
// credentials file.
func WithCredentialsFile(filename string) ClientOption {
	return withCredFile(filename)
}

// WithServiceAccountFile returns a ClientOption that uses a Google service
// account credentials file to authenticate.
//
// Deprecated: Use WithCredentialsFile instead.
func WithServiceAccountFile(filename string) ClientOption {
	return WithCredentialsFile(filename)
}

// WithCredentialsJSON returns a ClientOption that authenticates
// API calls with the given service account or refresh token JSON
// credentials.
func WithCredentialsJSON(p []byte) ClientOption {
	return withCredentialsJSON(p)
}

type withCredentialsJSON []byte

func (w withCredentialsJSON) Apply(o *internal.DialSettings) {
	o.CredentialsJSON = make([]byte, len(w))
	copy(o.CredentialsJSON, w)
}

// WithEndpoint returns a ClientOption that overrides the default endpoint
// to be used for a service.
func WithEndpoint(url string) ClientOption {
	return withEndpoint(url)
}

type withEndpoint string

func (w withEndpoint) Apply(o *internal.DialSettings) {
	o.Endpoint = string(w)
}

// WithScopes returns a ClientOption that overrides the default OAuth2 scopes
// to be used for a service.
func WithScopes(scope ...string) ClientOption {
	return withScopes(scope)
}

type withScopes []string

func (w withScopes) Apply(o *internal.DialSettings) {
	o.Scopes = make([]string, len(w))
	copy(o.Scopes, w)
}

// WithUserAgent returns a ClientOption that sets the User-Agent.
func WithUserAgent(ua string) ClientOption {
	return withUA(ua)
}

type withUA string

func (w withUA) Apply(o *internal.DialSettings) { o.UserAgent = string(w) }

// WithHTTPClient returns a ClientOption that specifies the HTTP client to use
// as the basis of communications. This option may only be used with services
// that support HTTP as their communication transport. When used, the
// WithHTTPClient option takes precedent over all other supplied options.
func WithHTTPClient(client *http.Client) ClientOption {
	return withHTTPClient{client}
}

type withHTTPClient struct{ client *http.Client }

func (w withHTTPClient) Apply(o *internal.DialSettings) {
	o.HTTPClient = w.client
}

// WithGRPCConn returns a ClientOption that specifies the gRPC client
// connection to use as the basis of communications. This option may only be
// used with services that support gRPC as their communication transport. When
// used, the WithGRPCConn option takes precedent over all other supplied
// options.
func WithGRPCConn(conn *grpc.ClientConn) ClientOption {
	return withGRPCConn{conn}
}

type withGRPCConn struct{ conn *grpc.ClientConn }

func (w withGRPCConn) Apply(o *internal.DialSettings) {
	o.GRPCConn = w.conn
}

// WithGRPCDialOption returns a ClientOption that appends a new grpc.DialOption
// to an underlying gRPC dial. It does not work with WithGRPCConn.
func WithGRPCDialOption(opt grpc.DialOption) ClientOption {
	return withGRPCDialOption{opt}
}

type withGRPCDialOption struct{ opt grpc.DialOption }

func (w withGRPCDialOption) Apply(o *internal.DialSettings) {
	o.GRPCDialOpts = append(o.GRPCDialOpts, w.opt)
}

// WithGRPCConnectionPool returns a ClientOption that creates a pool of gRPC
// connections that requests will be balanced between.
// This is an EXPERIMENTAL API and may be changed or removed in the future.
func WithGRPCConnectionPool(size int) ClientOption {
	return withGRPCConnectionPool(size)
}

type withGRPCConnectionPool int

func (w withGRPCConnectionPool) Apply(o *internal.DialSettings) {
	// balancer := grpc.RoundRobin(internal.NewPoolResolver(int(w), o))
	// o.GRPCDialOpts = append(o.GRPCDialOpts, grpc.WithBalancer(balancer))
}

// WithAPIKey returns a ClientOption that specifies an API key to be used
// as the basis for authentication.
//
// API Keys can only be used for JSON-over-HTTP APIs, including those under
// the import path google.golang.org/api/....
func WithAPIKey(apiKey string) ClientOption {
	return withAPIKey(apiKey)
}

type withAPIKey string

func (w withAPIKey) Apply(o *internal.DialSettings) { o.APIKey = string(w) }

// WithAudiences returns a ClientOption that specifies an audience to be used
// as the audience field ("aud") for the JWT token authentication.
func WithAudiences(audience ...string) ClientOption {
	return withAudiences(audience)
}

type withAudiences []string

func (w withAudiences) Apply(o *internal.DialSettings) {
	o.Audiences = make([]string, len(w))
	copy(o.Audiences, w)
}

// WithoutAuthentication returns a ClientOption that specifies that no
// authentication should be used. It is suitable only for testing and for
// accessing public resources, like public Google Cloud Storage buckets.
// It is an error to provide both WithoutAuthentication and any of WithAPIKey,
// WithTokenSource, WithCredentialsFile or WithServiceAccountFile.
func WithoutAuthentication() ClientOption {
	return withoutAuthentication{}
}

type withoutAuthentication struct{}

func (w withoutAuthentication) Apply(o *internal.DialSettings) { o.NoAuth = true }

// WithQuotaProject returns a ClientOption that specifies the project used
// for quota and billing purposes.
//
// For more information please read:
// https://cloud.google.com/apis/docs/system-parameters
func WithQuotaProject(quotaProject string) ClientOption {
	return withQuotaProject(quotaProject)
}

type withQuotaProject string

func (w withQuotaProject) Apply(o *internal.DialSettings) {
	o.QuotaProject = string(w)
}

// WithRequestReason returns a ClientOption that specifies a reason for
// making the request, which is intended to be recorded in audit logging.
// An example reason would be a support-case ticket number.
//
// For more information please read:
// https://cloud.google.com/apis/docs/system-parameters
func WithRequestReason(requestReason string) ClientOption {
	return withRequestReason(requestReason)
}

type withRequestReason string

func (w withRequestReason) Apply(o *internal.DialSettings) {
	o.RequestReason = string(w)
}

// WithTelemetryDisabled returns a ClientOption that disables default telemetry (OpenCensus)
// settings on gRPC and HTTP clients.
// An example reason would be to bind custom telemetry that overrides the defaults.
func WithTelemetryDisabled() ClientOption {
	return withTelemetryDisabledOption{}
}

type withTelemetryDisabledOption struct{}

func (w withTelemetryDisabledOption) Apply(o *internal.DialSettings) {
	o.TelemetryDisabled = true
}
`

**Comment by Niek-Okido** [comment] 2020-01-13 17:34
`func (w withGRPCConnectionPool) Apply(o *internal.DialSettings) {
	// balancer := grpc.RoundRobin(internal.NewPoolResolver(int(w), o))
	// o.GRPCDialOpts = append(o.GRPCDialOpts, grpc.WithBalancer(balancer))
}
` this is what i did and work for me

**Comment by Niek-Okido** [comment] 2020-01-13 17:40
if you get stumbled you can get message with me on discord : Okido#3690

**Comment by chadit** [comment] 2020-01-13 17:46
this also broke the googles own docs api for sheets.
https://developers.google.com/sheets/api/quickstart/go

**Comment by Fyb3roptik** [comment] 2020-01-13 19:11
I am unable to switch to Go Modules right now and this has our Production systems down! PLEASE FIX!!!!!

**Comment by codyoss** [comment] 2020-01-13 20:13
@Fyb3roptik I would recommend vendoring google.golang.org/grpc=google.golang.org/grpc@v1.26.0 as a workaround

**Comment by Fyb3roptik** [comment] 2020-01-13 20:28
This is being included by one of the many libraries we are using. Not sure which one, so this is NOT an option as said previously. All of our production servers are down because they all break on deployment currently.

**Comment by codyoss** [comment] 2020-01-13 20:34
Do you use any sort of dependency management? There are ways to make this work with tools like dep if you happen to be using that: https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-constrain-a-transitive-dependencys-version

**Comment by Fyb3roptik** [comment] 2020-01-13 20:47
No, we deploy to elastic beanstalk and use go get in the Dockerfile currently. I know there is a better way, but too bogged down to get to it =/

**Comment by Fercho120** [comment] 2020-01-13 20:51
@Niek-Okido After following your suggestion sadly I got another error:

./fileSystemHelpers.go:174:17: assignment mismatch: 3 variables but mimetype.DetectReader returns 2 values

Do you have any idea what could be causing this? Do you use go Modules or anything?

**Comment by codyoss** [comment] 2020-01-13 21:14
Thanks to the grpc, this should now be working if you are pulling head. We plan to address this issue quickly to no longer rely on the code that will be removed again.

**Comment by dfawley** [comment] 2020-01-13 21:17
Note that the replacement API is also still experimental, unfortunately.  It should not be referenced from any non-experimental packages, to avoid future breakages.  Hopefully there are non-experimental ways to accomplish the same things - we can discuss options offline if you would like.

**Comment by cosmin8905** [comment] 2020-01-13 21:45
TY Confirming working 👍  

`EE00683-MacBook-Pro:build cosmin$ go get -u -v  google.golang.org/api/option`
get "google.golang.org/api/option": found meta tag get.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://code.googlesource.com/google-api-go-client"} at //google.golang.org/api/option?go-get=1
get "google.golang.org/api/option": verifying non-authoritative meta tag
google.golang.org/api (download)
get "golang.org/x/oauth2": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at //golang.org/x/oauth2?go-get=1
golang.org/x/oauth2 (download)
get "golang.org/x/oauth2/internal": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at //golang.org/x/oauth2/internal?go-get=1
get "golang.org/x/oauth2/internal": verifying non-authoritative meta tag
get "golang.org/x/net/context/ctxhttp": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/context/ctxhttp?go-get=1
get "golang.org/x/net/context/ctxhttp": verifying non-authoritative meta tag
golang.org/x/net (download)
get "golang.org/x/oauth2/google": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at //golang.org/x/oauth2/google?go-get=1
get "golang.org/x/oauth2/google": verifying non-authoritative meta tag
get "cloud.google.com/go/compute/metadata": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at //cloud.google.com/go/compute/metadata?go-get=1
get "cloud.google.com/go/compute/metadata": verifying non-authoritative meta tag
cloud.google.com/go (download)


get "golang.org/x/oauth2/jws": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at //golang.org/x/oauth2/jws?go-get=1
get "golang.org/x/oauth2/jws": verifying non-authoritative meta tag
get "golang.org/x/oauth2/jwt": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at //golang.org/x/oauth2/jwt?go-get=1
get "golang.org/x/oauth2/jwt": verifying non-authoritative meta tag
get "google.golang.org/api/internal": found meta tag get.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://code.googlesource.com/google-api-go-client"} at //google.golang.org/api/internal?go-get=1
get "google.golang.org/api/internal": verifying non-authoritative meta tag
get "google.golang.org/grpc": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc?go-get=1
google.golang.org/grpc (download)
get "golang.org/x/net/trace": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/trace?go-get=1
get "golang.org/x/net/trace": verifying non-authoritative meta tag
get "golang.org/x/net/internal/timeseries": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/internal/timeseries?go-get=1
get "golang.org/x/net/internal/timeseries": verifying non-authoritative meta tag
get "google.golang.org/grpc/backoff": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/backoff?go-get=1
get "google.golang.org/grpc/backoff": verifying non-authoritative meta tag
get "google.golang.org/grpc/balancer": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/balancer?go-get=1
get "google.golang.org/grpc/balancer": verifying non-authoritative meta tag
get "google.golang.org/grpc/connectivity": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/connectivity?go-get=1
get "google.golang.org/grpc/connectivity": verifying non-authoritative meta tag
get "google.golang.org/grpc/grpclog": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/grpclog?go-get=1
get "google.golang.org/grpc/grpclog": verifying non-authoritative meta tag
get "google.golang.org/grpc/credentials": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/credentials?go-get=1
get "google.golang.org/grpc/credentials": verifying non-authoritative meta tag
github.com/golang/protobuf (download)
get "google.golang.org/grpc/credentials/internal": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/credentials/internal?go-get=1
get "google.golang.org/grpc/credentials/internal": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal?go-get=1
get "google.golang.org/grpc/internal": verifying non-authoritative meta tag
get "google.golang.org/grpc/metadata": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/metadata?go-get=1
get "google.golang.org/grpc/metadata": verifying non-authoritative meta tag
get "google.golang.org/grpc/resolver": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/resolver?go-get=1
get "google.golang.org/grpc/resolver": verifying non-authoritative meta tag
get "google.golang.org/grpc/attributes": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/attributes?go-get=1
get "google.golang.org/grpc/attributes": verifying non-authoritative meta tag
get "google.golang.org/grpc/serviceconfig": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/serviceconfig?go-get=1
get "google.golang.org/grpc/serviceconfig": verifying non-authoritative meta tag
get "google.golang.org/grpc/balancer/base": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/balancer/base?go-get=1
get "google.golang.org/grpc/balancer/base": verifying non-authoritative meta tag
get "google.golang.org/grpc/balancer/roundrobin": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/balancer/roundrobin?go-get=1
get "google.golang.org/grpc/balancer/roundrobin": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/grpcrand": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/grpcrand?go-get=1
get "google.golang.org/grpc/internal/grpcrand": verifying non-authoritative meta tag
get "google.golang.org/grpc/codes": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/codes?go-get=1
get "google.golang.org/grpc/codes": verifying non-authoritative meta tag
get "google.golang.org/grpc/encoding": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/encoding?go-get=1
get "google.golang.org/grpc/encoding": verifying non-authoritative meta tag
get "google.golang.org/grpc/encoding/proto": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/encoding/proto?go-get=1
get "google.golang.org/grpc/encoding/proto": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/backoff": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/backoff?go-get=1
get "google.golang.org/grpc/internal/backoff": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/balancerload": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/balancerload?go-get=1
get "google.golang.org/grpc/internal/balancerload": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/binarylog": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/binarylog?go-get=1
get "google.golang.org/grpc/internal/binarylog": verifying non-authoritative meta tag
get "google.golang.org/grpc/binarylog/grpc_binarylog_v1": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/binarylog/grpc_binarylog_v1?go-get=1
get "google.golang.org/grpc/binarylog/grpc_binarylog_v1": verifying non-authoritative meta tag
get "google.golang.org/grpc/status": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/status?go-get=1
get "google.golang.org/grpc/status": verifying non-authoritative meta tag
get "google.golang.org/genproto/googleapis/rpc/status": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at //google.golang.org/genproto/googleapis/rpc/status?go-get=1
get "google.golang.org/genproto/googleapis/rpc/status": verifying non-authoritative meta tag
google.golang.org/genproto (download)
get "google.golang.org/grpc/internal/buffer": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/buffer?go-get=1
get "google.golang.org/grpc/internal/buffer": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/channelz": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/channelz?go-get=1
get "google.golang.org/grpc/internal/channelz": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/envconfig": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/envconfig?go-get=1
get "google.golang.org/grpc/internal/envconfig": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/grpcsync": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/grpcsync?go-get=1
get "google.golang.org/grpc/internal/grpcsync": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/resolver/dns": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/resolver/dns?go-get=1
get "google.golang.org/grpc/internal/resolver/dns": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/resolver/passthrough": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/resolver/passthrough?go-get=1
get "google.golang.org/grpc/internal/resolver/passthrough": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/transport": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/transport?go-get=1
get "google.golang.org/grpc/internal/transport": verifying non-authoritative meta tag
get "golang.org/x/net/http2": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/http2?go-get=1
get "golang.org/x/net/http2": verifying non-authoritative meta tag
get "golang.org/x/net/http/httpguts": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/http/httpguts?go-get=1
get "golang.org/x/net/http/httpguts": verifying non-authoritative meta tag
get "golang.org/x/net/idna": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/idna?go-get=1
get "golang.org/x/net/idna": verifying non-authoritative meta tag
get "golang.org/x/text/secure/bidirule": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/secure/bidirule?go-get=1
get "golang.org/x/text/secure/bidirule": verifying non-authoritative meta tag
golang.org/x/text (download)
get "golang.org/x/text/transform": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
get "golang.org/x/text/unicode/bidi": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/unicode/bidi?go-get=1
get "golang.org/x/text/unicode/bidi": verifying non-authoritative meta tag
get "golang.org/x/text/unicode/norm": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
get "golang.org/x/net/http2/hpack": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/http2/hpack?go-get=1
get "golang.org/x/net/http2/hpack": verifying non-authoritative meta tag
get "google.golang.org/grpc/internal/syscall": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/internal/syscall?go-get=1
get "google.golang.org/grpc/internal/syscall": verifying non-authoritative meta tag
get "google.golang.org/grpc/keepalive": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/keepalive?go-get=1
get "google.golang.org/grpc/keepalive": verifying non-authoritative meta tag
get "google.golang.org/grpc/peer": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/peer?go-get=1
get "google.golang.org/grpc/peer": verifying non-authoritative meta tag
get "google.golang.org/grpc/stats": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/stats?go-get=1
get "google.golang.org/grpc/stats": verifying non-authoritative meta tag
get "google.golang.org/grpc/tap": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/tap?go-get=1
get "google.golang.org/grpc/tap": verifying non-authoritative meta tag
get "google.golang.org/grpc/naming": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at //google.golang.org/grpc/naming?go-get=1
get "google.golang.org/grpc/naming": verifying non-authoritative meta tag
google.golang.org/grpc/balancer
google.golang.org/grpc/balancer/base
google.golang.org/grpc/balancer/roundrobin
google.golang.org/grpc
google.golang.org/api/internal
google.golang.org/api/option

**Comment by Niek-Okido** [comment] 2020-01-13 23:03
> I am unable to switch to Go Modules right now and this has our Production systems down! PLEASE FIX!!!!!
contact me on Discord!! 

Okido#3690

**Comment by Niek-Okido** [comment] 2020-01-13 23:12
@Fercho120 can you contact me on discord ? Okido#3690 so we can look both on it .
and yeah i used Go modules from this .

**Comment by Fercho120** [comment] 2020-01-15 02:43
@Niek-Okido I've just read your response, thanks for your willingness to help, after some work I've realized that the error was caused by some changes introduced in golang's mime package last update, an problem that I've already solved and wasn't related to this issue.

**Comment by Fyb3roptik** [comment] 2020-01-16 02:57
I appreciate the quick response from everyone!

**Comment by broady** [comment] 2020-02-11 20:34
Quick update... Next steps:

- tag a release of all modules in google-cloud-go
- submit [CL 50573](https://code-review.googlesource.com/c/google-api-go-client/+/50573)
- tag a release of google-api-go-client

**Closed** 2020-03-03 03:11 UTC
Labels: priority: p1, type: process
