### ISSUE TITLE
functions, storage: events incoherent, and data for 2nd argument not well-defined

### ISSUE THREAD

**Issue by wmark** [googleapis/google-api-go-client#348] opened 2019-03-23 17:29 UTC
This concerns _cloud functions_ triggered by _storage buckets_. For details please see the deployment instruction below; to illustrate the issue I refer to the example function given below.

`cloud.google.com/go` is `v0.37.0` (because `v0.37.1` won't deploy → #345) and  
`google.golang.org/api` is `v0.1.0`

1. `meta, _ := metadata.FromContext(ctx); meta.EventType` does not match `storage.ObjectFinalizeEvent`, `storage.ObjectDeleteEvent`, and so on.
2. There's at least three different variants in the documentation for the **second argument to a cloud function**. Each time a subset of fields is used in the scope of the file (example source code in the web console, example under "storage", and another under the documentation of functions). In the pursuit of something pre-defined you'd run into this:
   - `storage.ObjectAttrs` will give an `INVALID_ARGUMENT` when deploying (and results in a crash when called), an error which is neither referenced in the documentation of _storage_ nor _functions_. (I didn't search through the low-level API docs.)
   - `google.golang.org/api/storage/v1#Object` gets not rejected, but is marked as **depreciated**. Neither fields `Acl` nor `Metadata` will be populated.

I'd love to see clear and unambiguous guidance as to what I can expect as second argument to such a _cloud function_ triggered by [a] _bucket_ [event((s)]. And the documentation being in sync with actual invocations.

1. Yet except in docs of the JSON_API_V1, there seems to be no well-defined struct for Go.
2. incoherent event types
    - `OBJECT_FINALIZE` here
    - `google.storage.object.finalize` there,
        - which is not defined anywhere as constant in the referenced packages
3. The documentation is misleading with regard to which events (docs: all) trigger a function deployed like this (practice: only `finalize`).

----
<details>
<summary>misleading output of: gcloud functions deploy --help</summar>

Please note the `every` in `every change`:

> --trigger-bucket=TRIGGER_BUCKET
> Google Cloud Storage bucket name. Every change in files in this
> bucket will trigger function execution.

</details>

<details>
<summary>gcloud deploy call</summary>

```console
$ gcloud functions deploy "on-bucket-changes" \
  --entry-point="OnBucketContentChange" \
  --runtime go111 \
  --trigger-bucket="gs://…"
```

</details>

<details>
<summary>example function triggered on "all" bucket changes</summary>

- Please note that only the `default` branch of the switch is taken.
- As deployed above only `google.storage.object.finalize` gets passed to this functions; all other events won't trigger it.

```go
package example

import (
        "context"
        "fmt"

        "cloud.google.com/go/functions/metadata"
        "cloud.google.com/go/storage"
        storageapi "google.golang.org/api/storage/v1"
)

// OnBucketContentChange is supposed to act on all events.
func OnBucketContentChange(ctx context.Context, e storageapi.Object) error {
        // e is specified under JSON_API_V1 here: https://cloud.google.com/storage/docs/pubsub-notifications#payload
        //
        // This will throw INVALID_ARGUMENT upon deployment (and crash on invocations):
        //   e storage.ObjectAttrs

        meta, err := metadata.FromContext(ctx)
        if err != nil {
                return fmt.Errorf("metadata.FromContext: %v", err)
        }

        // see https://cloud.google.com/storage/docs/pubsub-notifications#events
        switch meta.EventType {
        case storage.ObjectFinalizeEvent:
                fmt.Println("storage.ObjectFinalizeEvent")
        case storage.ObjectDeleteEvent:
                fmt.Println("storage.ObjectDeleteEvent")
        case storage.ObjectMetadataUpdateEvent, storage.ObjectArchiveEvent:
                fmt.Println("storage.ObjectMetadataUpdateEvent, storage.ObjectArchiveEvent")
                // 'Archive' is for the now obsolete copy if object versioning were enabled.
        default:
                fmt.Printf("meta.EventType unknown: %v\n", meta.EventType)
        }

        fmt.Printf("e is: -- %+v\n", e)
        return nil
}
```

</details>

**Comment by jadekler** [comment] 2019-03-26 14:06
@tbpg @broady @frankyn Do any of y'all have experience with this?

**Comment by stewblr** [comment] 2019-04-02 17:05
Hi wmark -- trying to understand the issue.

[This page](https://cloud.google.com/functions/docs/calling/storage) has a sample that shows how to set up a Cloud Storage function with a trigger corresponding to a particular event type.

It also links to the [event structure](https://cloud.google.com/functions/docs/calling/storage#event_structure) that your function should expect as the second argument.

**Comment by wmark** [comment] 2019-04-02 18:30
Hi @stewblr – thanks for looking into this. Reverting to original order:

1. There's the trigger type values („event types“ in your words) you're showing – mind I've complained that there's several variants published! – and there's these: https://cloud.google.com/storage/docs/pubsub-notifications#events
2. I did already find the „event structure“ you're (indirectly) referencing: https://cloud.google.com/storage/docs/json_api/v1/objects#resource  

- [ ] (Re 1) Ideally you'd clearly annotated one variant as *legacy/don't use anymore!*.
- [ ] (Re 1) Where (`*.go` or module) can I find those strings as constants?  
`storage.ObjectFinalizeEvent` is, as outlined and as I understand it, *legacy/obsolete*.
- [ ] Where can I find (2) defined as `struct`? Which `*.go` file or (non-depreciated) module has the complete and authoritative `struct`?
- [ ] (Not listed above.) Where can I find documentation for all error codes thrown by the Google Functions caller (the part that gives `INVALID_ARGUMENT` and similar on deployments; I guess after calling `reflect` upon first inspection of whatever the client (me) has uploaded).

**Comment by stewblr** [comment] 2019-04-03 22:01
Hopefully I can resolve some of this confusion.

> There's the trigger type values („event types“ in your words) you're showing – mind I've complained that there's several variants published! – and there's these: https://cloud.google.com/storage/docs/pubsub-notifications#events

Since you're trying to use these in the context of Cloud Functions, I would focus on those docs (see [the doc](https://cloud.google.com/functions/docs/calling/storage) I linked above if you're looking to use Cloud Storage with Cloud Functions). They list the [event types](https://cloud.google.com/functions/docs/calling/storage#event_types) that you can pass to the CLI to create the trigger/event binding.

> Not listed above.) Where can I find documentation for all error codes thrown by the Google Functions caller (the part that gives INVALID_ARGUMENT and similar on deployments; I guess after calling reflect upon first inspection of whatever the client (me) has uploaded).

If you have a reproducible test case that is producing an `INVALID_ARGUMENT` error, please share it. `INVALID_ARGUMENT` is not helpful and we should be giving back more helpful error messages.

>  (Re 1) Where (*.go or module) can I find those strings as constants?
storage.ObjectFinalizeEvent is, as outlined and as I understand it, legacy/obsolete.

Is it legacy/obsolete? I'm not aware that it is but would appreciate if you could point me to docs stating otherwise.

>  Where can I find (2) defined as struct? Which *.go file or (non-depreciated) module has the complete and authoritative struct?

There isn't a *.go file that defines this struct for you. You *should* be able to just define this struct by referring the JSON payload mentioned [here](https://cloud.google.com/storage/docs/json_api/v1/objects#resource). Is there a particular field that is causing trouble?

--


I did notice that one part of our docs still mentioned the `trigger-bucket` method of specifying the event type and I filed a bug report to update that to the newer `trigger-resource`/`trigger-event` approach shown on [the storage page](https://cloud.google.com/functions/docs/calling/storage).

**Comment by jadekler** [comment] 2019-06-11 19:11
Closing this since the conversation seems to have stalled. Let me know if there's more to discuss here and I'll be happy to re-open.

**Closed by jadekler** 2019-06-11 19:11 UTC
Labels: type: question
