### ISSUE TITLE
NewService with option.WithTokenSource error: could not find default credentials

### ISSUE THREAD

**Issue by bubenkoff** [googleapis/google-api-go-client#2576] opened 2024-05-09 07:57 UTC
Since v0.178.0 I am getting an seemingly unreasonable auth error when using  option.WithTokenSource: credentials: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information
By checking the provided article it doesn't seem to apply for the oauth token authentication, so why does it still require ADC setup even when WithTokenSource is used?

#### Environment details

  - Programming language: golang
  - OS: linux
  - Language runtime version: 1.21
  - Package version: v0.178.0

#### Steps to reproduce

  1. Use drive.NewService(ctx, option.WithTokenSource(config.TokenSource(ctx, token)))

**Comment by rofleksey** [comment] 2024-05-09 14:28
Try this

```
client := googleConfig.Client(ctx, token)
tokenSource := googleConfig.TokenSource(ctx, token)

svc, err := <you service>.NewService(
  ctx,
  option.WithHTTPClient(client),
  option.WithTokenSource(tokenSource),
)
```

**Comment by codyoss** [comment] 2024-05-09 15:13
Thanks for the report. This is likely due to a rollout that started in the latest version of this client, sorry for the inconvenience.  As a workaround reverting to the previous version should fix things. I tried a basic example using option.WithTokenSource and the drive API and was unable to reproduce this issue. Could you please share a minimal reproducer for this. Thank you

**Comment by quartzmo** [comment] 2024-05-09 18:17
I also followed the Drive Quickstart at  https://developers.google.com/drive/api/quickstart/go, which goes to the browser to get the token, and then ran @codyoss's example above. I too was unable to reproduce this issue. Hoping for a complete code sample soon from @bubenkoff.

<details>
  <summary>go.mod</summary> 
  <pre>
module example.com/drive

go 1.22.0

require (
	golang.org/x/oauth2 v0.20.0
	google.golang.org/api v0.178.0
)

require (
	cloud.google.com/go/auth v0.3.0 // indirect
	cloud.google.com/go/auth/oauth2adapt v0.2.2 // indirect
	cloud.google.com/go/compute/metadata v0.3.0 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/go-logr/logr v1.4.1 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
	github.com/golang/protobuf v1.5.4 // indirect
	github.com/google/s2a-go v0.1.7 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/googleapis/enterprise-certificate-proxy v0.3.2 // indirect
	github.com/googleapis/gax-go/v2 v2.12.4 // indirect
	go.opencensus.io v0.24.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.49.0 // indirect
	go.opentelemetry.io/otel v1.24.0 // indirect
	go.opentelemetry.io/otel/metric v1.24.0 // indirect
	go.opentelemetry.io/otel/trace v1.24.0 // indirect
	golang.org/x/crypto v0.22.0 // indirect
	golang.org/x/net v0.24.0 // indirect
	golang.org/x/sys v0.19.0 // indirect
	golang.org/x/text v0.14.0 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240429193739-8cf5692501f6 // indirect
	google.golang.org/grpc v1.63.2 // indirect
	google.golang.org/protobuf v1.34.1 // indirect
)
</pre>
</details>

**Comment by bubenkoff** [comment] 2024-05-09 20:03
The error happens in this function

```
// FindDefaultCredentialsWithParams searches for "Application Default Credentials".
//
// It looks for credentials in the following places,
// preferring the first location found:
//
//  1. A JSON file whose path is specified by the
//     GOOGLE_APPLICATION_CREDENTIALS environment variable.
//     For workload identity federation, refer to
//     https://cloud.google.com/iam/docs/how-to#using-workload-identity-federation on
//     how to generate the JSON configuration file for on-prem/non-Google cloud
//     platforms.
//  2. A JSON file in a location known to the gcloud command-line tool.
//     On Windows, this is %APPDATA%/gcloud/application_default_credentials.json.
//     On other systems, $HOME/.config/gcloud/application_default_credentials.json.
//  3. On Google Compute Engine, Google App Engine standard second generation runtimes
//     (>= Go 1.11), and Google App Engine flexible environment, it fetches
//     credentials from the metadata server.
func FindDefaultCredentialsWithParams(ctx context.Context, params CredentialsParams) (*Credentials, error) {
	// Make defensive copy of the slices in params.
	params = params.deepCopy()

```

when the NewService is called.
If you are not able to reproduce the issue, then you might have the creds file / env variable present on your system, is that the case?
In my case, only the token is provided, nothing else. 
So it's more about the environment, not the particular code.

**Comment by codyoss** [comment] 2024-05-09 21:52
I believe this should be fixed now in https://github.com/googleapis/google-api-go-client/releases/tag/v0.179.0 . Would you mind trying to upgrade and let us know if that fixed the issue for you?

**Comment by bubenkoff** [comment] 2024-05-10 10:34
@codyoss yes, it works with the 0.179.0, that you so much!

**Comment by codyoss** [comment] 2024-05-10 16:17
Awesome, sorry for the inconvenience. And thank you again for the report!

**Closed by codyoss** 2024-05-10 16:17 UTC
Labels: type: bug, priority: p1, needs more info
