### ISSUE TITLE
admob: networkreport generate returns json unmarshal error

### ISSUE THREAD

**Issue by MrNullPoint** [googleapis/google-api-go-client#1182] opened 2021-08-25 09:23 UTC
#### Environment details

  - Programming language: golang
  - OS: macos
  - Language runtime version: go version go1.15.5 darwin/amd64
  - Package version: master

#### Steps to reproduce

  1. call admob network.report
  2. it returns error ` json: cannot unmarshal array into Go value of type admob.GenerateNetworkReportResponse`
  
**sample code**
```golang
        admobService, err := admob.NewService(ctx, option.WithTokenSource(config.TokenSource(ctx, token)))
	if err != nil {
		log.Fatalf("new service err:%v", err)
	}

	res, err := admobService.Accounts.NetworkReport.Generate("accounts/pub-2200607303212623", &admob.GenerateNetworkReportRequest{
		ReportSpec: &admob.NetworkReportSpec{
			DateRange: &admob.DateRange{
				EndDate: &admob.Date{
					Day:   21,
					Month: 8,
					Year:  2021,
				},
				StartDate: &admob.Date{
					Day:   20,
					Month: 8,
					Year:  2021,
				},
			},
			Dimensions:    []string{"DATE", "APP", "COUNTRY"},
			MaxReportRows: 100000,
			Metrics:       []string{"CLICKS", "ESTIMATED_EARNINGS"},
		},
	}).Do()

        log.Printf("%+v, %+v", res, err)
```

**bug reason**
<img width="1601" alt="75FD97E9-7B56-43CB-93A2-F32FFB5E87F6" src="https://user-images.githubusercontent.com/27116075/130764583-a10bcf1d-7e1e-4394-beeb-e02953a43d2b.png">

**Comment by codyoss** [comment] 2021-08-25 13:54
This looks like a duplicate of #468. This is being tracked internally as b/184875907. The issue appears to be that this is actually a streaming RPC which this client does not natively support. I have commented on b/184875907 about this and asked if we can get a workaround while other options are being explored.

**Comment by codyoss** [comment] 2021-09-14 19:53
Closing this issue as a duplicate for now. I will update the linked issue should I get an update.

**Closed** 2021-09-21 17:24 UTC
Labels: priority: p2, type: bug, external

**Comment by gif-gif** [comment] 2024-10-29 11:55
google api response is :
<img width="801" alt="image" src="https://github.com/user-attachments/assets/53de8022-79d5-4b11-8ed7-b5bdb61ea6c2">

same problem for me, how to solve it ? thks
