### ISSUE TITLE
AccountsNetworkReportGenerateCall Do function returns an arrray of GenerateNetworkReportResponse ?

### ISSUE THREAD

**Issue by partha2312** [googleapis/google-api-go-client#734] opened 2020-10-30 18:24 UTC
Hello,

I am trying to integrate AdMob v1 API to generate AdMob reports. 

My Code
```
admobService, err := am.NewService(context.Background(), option.WithScopes("https://www.googleapis.com/auth/admob.report"), authOption)
if err != nil {
     panic(err)
}
reportSpec := &am.NetworkReportSpec{
    Dimensions: []string{"AD_UNIT"},
    DateRange: &am.DateRange{
	StartDate: &am.Date{Day: 27, Month: 10, Year: 2020},
	EndDate:   &am.Date{Day: 28, Month: 10, Year: 2020},
    },
    Metrics: []string{"ESTIMATED_EARNINGS"},
        LocalizationSettings: &am.LocalizationSettings{
	    CurrencyCode: "USD",
	},
    }
reportSvc := am.NewAccountsNetworkReportService(admobService)
req := reportSvc.Generate("accounts/pub-xxxxxxxxx", &am.GenerateNetworkReportRequest{
	ReportSpec: reportSpec,
})

resp, err := req.Do()
if err != nil {
    fmt.Println(err)
    return
}
fmt.Println(fmt.Sprintf("%+v", resp))
```

I am getting the following error thrown from [here](https://github.com/googleapis/google-api-go-client/blob/master/admob/v1/admob-gen.go#L1993)

```
json: cannot unmarshal array into Go value of type admob.GenerateNetworkReportResponse
```

I tried the following code before this [line](https://github.com/googleapis/google-api-go-client/blob/master/admob/v1/admob-gen.go#L1984)
```
dummy := make([]GenerateNetworkReportResponse, 0) 
err = json.NewDecoder(res.Body).Decode(&dummy)
// tried printing dummy
```
I was able to print the result. The response was in the form of array of concrete type (GenerateNetworkReportResponse).
Also I can see the [GenerateNetworkReportResponse](https://github.com/googleapis/google-api-go-client/blob/01545629cb6e2847400bcc7187e0434793e693af/admob/v1/admob-gen.go#L381) type has only one Row type as its field.

Am I missing something here or the decode should be done with the array type ?

PS: The Java example [here](https://github.com/googleads/googleads-admob-api-samples/blob/master/java/v1/src/main/java/com/google/api/services/samples/admob/reports/GenerateNetworkReport.java#L62) is trying to decode the stream to an array type too. So wanted to confirm.

**Comment by codyoss** [comment] 2020-11-02 15:42
Hey, you are right. This is a duplicate of #468. There is an internal issue filled that I was re-ping.

**Closed by codyoss** 2020-11-02 15:42 UTC
Labels: api: ads, type: question

**Comment by codyoss** [comment] 2020-11-02 15:43
I will comment back on the original bug if I hear an update.

**Comment by partha2312** [comment] 2020-11-02 15:48
> I will comment back on the original bug if I hear an update.

Thanks.
