### ISSUE TITLE
Add error helper methods like IsNotFound, IsAlreadyExists, etc.

### ISSUE THREAD

**Issue by ImJasonH** [googleapis/google-api-go-client#329] opened 2019-01-28 19:59 UTC
Using these libraries, in order to determine whether an operation failed due to a particular condition, typically we do something like:

```go
if _, err := svc.Buckets.Get(bucketName).Do(); err != nil {
  if herr, ok := err.(*googleapi.Error); ok && herr.Code == http.StatusNotFound {
    log.Println("bucket doesn't exist")
  }
  log.Printf("some other error getting bucket: %s", err)
}
```

or

```go
if _, err := svc.Buckets.Insert(bucketName, bucket).Do(); err != nil {
  if herr, ok := err.(*googleapi.Error); ok && herr.Code == http.StatusConflict {
    log.Println("bucket already exists")
  }
  log.Printf("some other error inserting bucket: %s", err)
}
```

It could be helpful if this library provided helper methods for these cases, so that callers could instead write:

```go
if _, err := svc.Buckets.Insert(bucketName, bucket).Do(); googleapi.IsNotExists(err) {
  log.Println("bucket already exists")
} else if err != nil {
  log.Printf("some other error inserting bucket: %s", err)
}
```

As prior art, the Kubernetes API clients provide a lot of these methods in [`k8s.io/apimachinery/pkg/api/errors`](https://godoc.org/k8s.io/apimachinery/pkg/api/errors).

If this is a reasonable addition to the library I'd be happy to contribute a PR to add them, with your naming/package guidance.

**Comment by jadekler** [comment] 2019-01-28 20:32
Unfortunately this doesn't fit super cleanly. Some of our clients are HTTP/1 with errors like 404 Does Not Exist, whilst others are gRPC with errors like [NotFound](https://github.com/grpc/grpc-go/blob/6086f8d68f83701fc00a9549c30c2b48861c8a6f/codes/codes.go#L60). This particular case is easy to consider equivalent, but many others are difficult (there's no HTTP equivalent of [Aborted](https://github.com/grpc/grpc-go/blob/6086f8d68f83701fc00a9549c30c2b48861c8a6f/codes/codes.go#L105), or gRPC equivalent of things like 409 Conflict).

I think if we did this we'd need to add methods for both, but I think that'd be pretty confusing for users. Given that and the fact that these are quite easy to implement as-needed by users, I lean towards letting users build the wrapping that suits them.

**Comment by ImJasonH** [comment] 2019-01-28 20:38
Thanks for your response, that's really helpful, and I hadn't considered that.

How does a user handle a not-found error when the underlying API request is a gRPC request? The [`googleapi.Error`](https://godoc.org/google.golang.org/api/googleapi#Error) type seems to be HTTP-specific.

However it's done, I could imagine an `IsNotExists` method could inspect and handle either the HTTP-flavored not-found or the gRPC-flavored not-found, without bothering the caller with which flavor it was.

`googleapi.IsAborted(err)` could either be omitted due to its uneven support between the flavors, or it could always `return false` if the error is HTTP-flavored.

**Comment by jadekler** [comment] 2019-01-28 23:02
@ImJasonH Users can use gRPC's [`status`](https://godoc.org/google.golang.org/grpc/status) package.

And, you're right, there's some grey area that's doable. Regrettably we're pretty understaffed at the moment and unable to investigate too deeply. I'll leave this issue open for further comments or for when we have time to swing back around to this.

**Comment by jadekler** [comment] 2019-12-03 16:53
Looks like after almost a year there are no other major requests for this. Since it seems fairly easy (though tedious) to reproduce this functionality, I'll close this for now. Happy to continue the conversation though.

**Closed by jadekler** 2019-12-03 16:53 UTC
Labels: type: feature request

**Comment by mykter** [comment] 2021-02-05 12:50
For what it's worth the cast and then code check approach wasn't obvious to me: it might be helpful to include it in the README or examples.

**Comment by codyoss** [comment] 2021-02-09 18:48
@mykter Thanks for the suggestion: https://github.com/googleapis/google-api-go-client/pull/867
