### ISSUE TITLE
admob/v1 networkReport:generate   fails on API response deserialization  

### ISSUE THREAD

**Issue by micshome** [googleapis/google-api-go-client#468] opened 2020-04-17 17:09 UTC
Service call service.Accounts.NetworkReport.Generate(...).Do() returns GenerateNetworkReportResponse response 
GenerateNetworkReportResponse struct contains one field 
**Row *ReportRow `json:"row,omitempty"`**
But, actual response from Google api contains []*ReportRow, and method Do() fails with **array** deserialization error

**Comment by micshome** [comment] 2020-04-17 18:45
Generally, it should be []*GenerateNetworkReportResponse , not []*ReportRow

**Comment by codyoss** [comment] 2020-04-20 17:11
@micshome Thanks for the report. This client is completely generated, so it is actually the spec that is wrong in this case. There is not much I can due, but I did open up a bug with a backend team to investigate the issue. I will report back here when I hear more.

**Comment by codyoss** [comment] 2020-09-11 15:13
Closing as bug has been reported internally: 154313078. There is nothing more to due from this libraries perspective.

**Closed by codyoss** 2020-09-11 15:13 UTC
Labels: api: ads, type: cleanup

**Comment by jostyee** [comment] 2021-11-19 08:12
@codyoss any update?

**Comment by codyoss** [comment] 2021-11-19 15:37
@jostyee, Just checked and not much to share. I believe the issue is due to the fact this is actually a streaming API. I will try to post back if I hear more.
