### ISSUE TITLE
[api/drive/v3] No substitute to deprecated ResumableMedia, ProgressUpdater still implemented but can't be used without it

### ISSUE THREAD

**Issue by steph9009** [googleapis/google-api-go-client#801] opened 2020-12-17 01:12 UTC
[ResumableMedia](https://pkg.go.dev/google.golang.org/api/drive/v3#FilesCreateCall.ResumableMedia) function is deprecated in v3 of Drive API, but if i understood correctly it's the only way to upload a file in chunks (and to resume it in case of failure) and there's no provided substitute.

Furthermore, by deprecating ResumableMedia, [ProgressUpdater](https://pkg.go.dev/google.golang.org/api/drive/v3#FilesUpdateCall.ProgressUpdater) is a sort of "orphan function", since it doesn't work with Media but it's still implemented and can't be used without ResumableMedia.

Is there any other solution to use ProgressUpdater, for example with the "simple" [Media](https://pkg.go.dev/google.golang.org/api/drive/v3#FilesUpdateCall.Media), like ResumableMedia comment suggests to adopt?

**Comment by codyoss** [comment] 2020-12-17 15:50
Currently there is not. Closing as a dupe of #452.

**Comment by codyoss** [comment] 2020-12-17 15:50
If there is extra context that is not in the other issue, fell free to inline it there. Thanks!

**Closed by codyoss** 2020-12-17 15:50 UTC

**Comment by steph9009** [comment] 2020-12-17 15:57
i'm truly sorry for duplicated issue: i searched before opening it, i swear... 😔

**Comment by codyoss** [comment] 2020-12-17 16:21
No worries!
