### ISSUE TITLE
drive: FilesCreateCall does not support uploading zip files 

### ISSUE THREAD

**Issue by hmvhamide** [googleapis/google-api-go-client#454] opened 2020-02-20 18:03 UTC
It gives "Error 400 Bad Request" when the content passed by Media() is a zip/tar file.

**Comment by tbpg** [comment] 2020-02-20 18:09
Would you mind sharing the code you're using so we can reproduce+debug?

**Comment by hmvhamide** [comment] 2020-02-21 16:33
I modified example/main.go to reproduce the bug:
[main.go.txt](https://github.com/googleapis/google-api-go-client/files/4237032/main.go.txt)
rename the file back to main.go and run it with parameters:
 ./main -clientid=<client_id> -secret=<secret_id> <a zip file name> x.zip <a drive folder id to upload to>

This is what it returns:
 2020/02/21 11:29:24 Got drive.File, err: (*drive.File)(nil), googleapi: Error 400: Bad Request, badRequest

It works OK with other file types (image, pdf, ...)

**Comment by tbpg** [comment] 2020-02-21 19:57
Looks like the MIME type in that file is `application/vnd.google-apps.file`. From https://pkg.go.dev/google.golang.org/api/drive/v3, it sounds like you might need to customize that (or omit it). Otherwise, it will try to be imported, which may not work with zip files.

(I haven't used this API, so this is just an idea. :smile:)

**Comment by hmvhamide** [comment] 2020-02-21 20:32
Thanks for the tip. It worked :))

**Comment by tbpg** [comment] 2020-02-21 20:36
Woohoo! Glad it worked. Let us know if you have any other issues.

**Comment by codyoss** [comment] 2020-06-05 14:05
Closing as issue seems resolved.

**Closed by codyoss** 2020-06-05 14:05 UTC
Labels: api: drive, needs more info, type: question
