### ISSUE TITLE
Compute: How to filter instances based on networkInterfaces

### ISSUE THREAD

**Issue by rodrigopavan** [googleapis/google-api-go-client#815] opened 2021-01-05 15:23 UTC
How can I/It's possible filter instances base on network attribute inside networkInterfaces?

I've tried a few things like:
req := c.ComputeService.Instances.List(projectID, zoneName).Filter('networkInterfaces[0].network=" + networkSelfLink + "')

req := c.ComputeService.Instances.List(projectID, zoneName).Filter('networkInterfaces.network=" + networkSelfLink + "')

req := c.ComputeService.Instances.List(projectID, zoneName).Filter('networkInterfaces[].network=" + networkSelfLink + "')

req := c.ComputeService.Instances.List(projectID, zoneName).Filter('items[].networkInterfaces[].network=" + networkSelfLink + "')

But, none of them works, I always receive an:
`Invalid value for field 'filter': 'networkInterfaces[0].network="https://www.googleapis.com/compute/v1/projects/simreplicacao/global/networks/default"'. Invalid list filter expression.`

`{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'filter': 'networkInterfaces[].network=\"https://www.googleapis.com/compute/v1/projects/ns1-ddi-integration-proj-01/global/networks/default\"'. Invalid list filter expression.",
    "errors": [
      {
        "message": "Invalid value for field 'filter': 'networkInterfaces[].network=\"https://www.googleapis.com/compute/v1/projects/ns1-ddi-integration-proj-01/global/networks/default\"'. Invalid list filter expression.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}`

`{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'filter': 'items[].networkInterfaces[].network=\"https://www.googleapis.com/compute/v1/projects/ns1-ddi-integration-proj-01/global/networks/default\"'. Invalid list filter expression.",
    "errors": [
      {
        "message": "Invalid value for field 'filter': 'items[].networkInterfaces[].network=\"https://www.googleapis.com/compute/v1/projects/ns1-ddi-integration-proj-01/global/networks/default\"'. Invalid list filter expression.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
`

**Comment by codyoss** [comment] 2021-01-05 15:43
Closing as duplicate of #813. Let's keep all discussion on one issue.

**Closed by codyoss** 2021-01-05 15:43 UTC
Labels: api: compute

**Comment by rodrigopavan** [comment] 2021-01-05 15:46
@codyoss , that one was closed, can you reopen?
