### ISSUE TITLE
"Error 400: Missing/Invalid attribute value: id, invalid" Occurs When Getting a Google Group that I Manage

### ISSUE THREAD

**Issue by kwesiRutledge** [googleapis/google-api-go-client#710] opened 2020-10-19 02:14 UTC
I am running a command of the flavor:

`r, err := groupsSrv.Groups.Get("googleGroupIDGoesHere").Do()`

where groupsSrv is a service created by the function groupssettings.New(). After running it, I always receive the error: "Error 400: Missing/Invalid attribute value: id, invalid". I have no idea why I'm getting this error. I am a "manager" for the group and can clearly see it when I log into the new google groups. I suspect something is flawed in my understanding, but maybe it's the code?

I've tried multiple iterations of the googleGroupID, but from what I can tell the first thing that I tried (i.e. the string of characters which precedes the "@googlegroups.com" part of the email address) was correct. I am curious to know what exactly is going wrong, but can't seem to find it by digging through the groupsSettings library. Is there something that I'm obviously doing wrong?

**Comment by codyoss** [comment] 2020-10-19 14:09
Dupe of #711

**Closed by codyoss** 2020-10-19 14:09 UTC
