### ISSUE TITLE
Querying managed Prometheus metrics error: json: cannot unmarshal object into Go struct field HttpBody.data of type string

### ISSUE THREAD

**Issue by veggiemonk** [googleapis/google-api-go-client#2304] opened 2023-12-13 15:34 UTC
Maybe it is something I did wrong, I couldn't find an example on how to query Google Managed Prometheus programmatically.

The error occurs because the `Data` field of `HttpBody` of type string which cause decoding JSON to fail while the request has succeeded (status 200). See https://github.com/googleapis/google-api-go-client/blob/main/monitoring/v1/monitoring-gen.go#L1518
After checking the header of the response, `Content-Type` is `application/json`

Could you recommend a way to query metrics without a front-end ? 

Much appreciated

#### Environment details

  - Programming language: Go 
  - OS: linux/amd64
  - Language runtime version: go1.21.5 
  - Package version: google.golang.org/api v0.154.0

#### Steps to reproduce

  1. Replace "XXX_project_id_XXX" with a project ID where Google Managed Prometheus is enabled.

```go
package main

import (
	"context"
	"fmt"
	"testing"
	"time"

	monv1 "google.golang.org/api/monitoring/v1"
)

func main() {
	fmt.Println("Hello, 世界")
}

func TestPromMetrics(t *testing.T) {
	ctx := context.Background()
	svc, err := monv1.NewService(ctx)
	if err != nil {
		t.Fatal(err)
	}
	s := monv1.NewProjectsLocationPrometheusApiV1Service(svc)
	q := &monv1.QueryRangeRequest{
		Query:   "agones_gameservers_total",
		Start:   time.Now().UTC().Add(-5 * time.Minute).Format(time.RFC3339),
		End:     time.Now().UTC().Format(time.RFC3339),
		Step:    "60s",
		Timeout: "60s",
	}
	resp, err := s.QueryRange("projects/XXX_project_id_XXX", "global", q).Do()
	if err != nil {
		t.Fatal(err, resp)
	}
	t.Logf("%#v", resp)
}
```
  2. Set up [Application Default Credentials](https://cloud.google.com/docs/authentication/provide-credentials-adc)
  3. Run  `go test -run TestPromMetrics` 

The full error message:

```
--- FAIL: TestPromMetrics (0.23s)
    metrics_test.go:39: json: cannot unmarshal object into Go struct field HttpBody.data of type string <nil>
FAIL
exit status 1
```

**Comment by veggiemonk** [comment] 2023-12-13 16:26
By forming the query manually it works:

```go
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"testing"
	"time"

	monv1 "google.golang.org/api/monitoring/v1"
	"google.golang.org/api/option"
	apihttp "google.golang.org/api/transport/http"
)

func main() {
	fmt.Println("Hello, 世界")
}

const ProjectID = "XXX"

func TestPromMetrics(t *testing.T) {
	opts := []option.ClientOption{
		option.WithScopes("https://www.googleapis.com/auth/monitoring.read"),
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	targetx := fmt.Sprintf("https://monitoring.googleapis.com/v1/projects/%s/location/global/prometheus", projectID)
	transport, err := apihttp.NewTransport(ctx, http.DefaultTransport, opts...)
	if err != nil {
		t.Fatal("create HTTP transport", "err", err)
	}
	client := http.Client{Transport: transport}
	u, err := url.Parse(targetx)
	if err != nil {
		t.Fatal("parse target URL", "err", err)
	}
	u.Path = path.Join(u.Path, "/api/v1/query_range")
	q := &monv1.QueryRangeRequest{
		Query:   "up",
		Start:   time.Now().UTC().Add(-5 * time.Minute).Format(time.RFC3339),
		End:     time.Now().UTC().Format(time.RFC3339),
		Step:    "60s",
		Timeout: "60s",
		// ForceSendFields: nil,
		// NullFields:      nil,
	}
	body, err := json.Marshal(q)
	if err != nil {
		t.Fatal("marshal query", "err", err)
	}

	newReq, err := http.NewRequestWithContext(ctx, http.MethodPost, u.String(), bytes.NewReader(body))
	resp, err := client.Do(newReq)
	if err != nil {
		t.Fatal("do request", "err", err)
	}
	defer resp.Body.Close()
	res, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatal("read response", "err", err)
	}
	t.Log(string(res))
}

```

**Comment by quartzmo** [comment] 2023-12-18 18:21
@veggiemonk,

Thank you for reporting this issue. 

> I couldn't find an example on how to query Google Managed Prometheus programmatically.

I looked through the samples in https://github.com/GoogleCloudPlatform/golang-samples/tree/main/monitoring but couldn't find anything for queries.

**Comment by quartzmo** [comment] 2023-12-18 18:39
@veggiemonk,

Thank you for providing the manual workaround.

Question: Can https://pkg.go.dev/cloud.google.com/go/monitoring be used for this use case?

Unfortunately, due to the maintenance mode status of this project, I won't be able to prioritize reproducing this issue right now. If you can still reproduce it, can you by any chance provide a deeper analysis of where the `json` error is occurring in the client library and what the fix might be?

**Comment by veggiemonk** [comment] 2023-12-26 12:57
@quartzmo 

> Question: Can https://pkg.go.dev/cloud.google.com/go/monitoring be used for this use case?

That package is for dealing with metrics stored in Cloud Operations as far as I understood. The metrics I used are store in Google Managed Prometheus which, apparently, is a different APIs. 



> can you by any chance provide a deeper analysis of where the `json` error is occurring in the client library and what the fix might be?

The error occurs because the `Data` field of `HttpBody` of type string which cause decoding JSON to fail while the request has succeeded (status 200). See https://github.com/googleapis/google-api-go-client/blob/main/monitoring/v1/monitoring-gen.go#L1518
The field should be of type `[]byte` as the error states:
`json: cannot unmarshal object into Go struct field HttpBody.data of type string`

That's the fix as far as I can tell.

**Comment by quartzmo** [comment] 2024-01-03 17:01
@veggiemonk Thank you for the link to the incorrect type. This is helpful, I will continue to investigate.

**Comment by codyoss** [comment] 2024-06-10 18:33
Closing as this issue has had not recent traffic, feel free to reopen if you are still having this problem.

**Comment by hanneshayashi** [comment] 2024-08-15 15:01
Just ran into this issue today so this is still relevant. I would love to use the new /apiv3/v2 for this but it doesn't expose anything that can be used to actually run PromQL. I don't even use managed Prometheus but I still need to query the monitoring API with a PromQL query for my use case.

**Comment by quartzmo** [comment] 2024-08-16 22:29
@hanneshayashi Are you also using `QueryRange`? Can you try running a PromQL query with `Query` and `QueryExemplars` if it's not too much trouble, to see if the same decoding problem ("HttpBody.data of type string") occurs?

**Comment by hanneshayashi** [comment] 2024-08-17 02:35
Yes, I am using QueryRange and I also ended up using a similar workaround to the above. I will try the other methods as well but I won't be able to before Monday.

**Comment by hanneshayashi** [comment] 2024-08-19 06:36
@quartzmo I just tried `Query` and `QueryExemplars` and they both returned the same error:

> 2024/08/19 08:34:53 json: cannot unmarshal array into Go struct field HttpBody.data of type string

**Comment by quartzmo** [comment] 2024-08-20 20:36
@hanneshayashi Thanks for verifying that. I doubt there will be any quick fix for this issue, but I will continue to investigate.

**Comment by hanneshayashi** [comment] 2024-08-21 07:51
@quartzmo I thought @veggiemonk already identified the cause in his original comment with `Data` being of type `string` instead of `[]byte` at https://github.com/googleapis/google-api-go-client/blob/08bc73375a4fea699980817e0a40329ce2310e0f/monitoring/v1/monitoring-gen.go#L1518 (this links to `v0.154.0`, the current position should be https://github.com/googleapis/google-api-go-client/blob/d994b67a3504af5d837903cf647e795744681445/monitoring/v1/monitoring-gen.go#L1414 for `v0.193.0`)

**Comment by codyoss** [comment] 2024-08-21 17:53
Have not looked into the full details, but this seems directly related to https://github.com/googleapis/google-api-go-client/issues/346

**Comment by codyoss** [comment] 2024-08-21 21:19
Looking into this a little more a quick fix for this would be to change HttpBody.Data to `any` instead of `string`. We can't use `[]byte` because the returned data is a json object that does not map to bytes.

**Comment by quartzmo** [comment] 2024-08-21 23:18
The following RPC methods all share the `HttpBody` response type. Will it be correct to apply the fix of changing `HttpBody.Data` from `string` to `any` for *all* of them?

* `Labels`
* `Query`
* `QueryExemplars`
* `QueryRange`
* `Series`
* `Values`
* `MetadataList`

**Comment by codyoss** [comment] 2024-08-22 15:36
This seems correct to me. proceeding with PR

**Closed** 2024-08-22 15:48 UTC
Labels: priority: p2, type: bug
