### ISSUE TITLE
Go get gensupport broken

### ISSUE THREAD

**Issue by d1vi** [googleapis/google-api-go-client#398] opened 2019-09-11 19:26 UTC
This can be replicated by doing 

```bash
go get -d "google.golang.org/api/gensupport"
```
with output:

```
package google.golang.org/api/gensupport: cannot find package "google.golang.org/api/gensupport" in any of:
	/usr/local/go/src/google.golang.org/api/gensupport (from $GOROOT)
	/home/username/go/src/google.golang.org/api/gensupport (from $GOPATH)
```

Here the output while running
```bash
go get -v  ./...
```
```
Fetching https://google.golang.org/api/gensupport?go-get=1
Parsing meta tags from https://google.golang.org/api/gensupport?go-get=1 (status code 200)
get "google.golang.org/api/gensupport": found meta tag get.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://code.googlesource.com/google-api-go-client"} at https://google.golang.org/api/gensupport?go-get=1
get "google.golang.org/api/gensupport": verifying non-authoritative meta tag
Fetching https://google.golang.org/api?go-get=1
Parsing meta tags from https://google.golang.org/api?go-get=1 (status code 200)
google.golang.org/api (download)
package google.golang.org/api/gensupport: cannot find package "google.golang.org/api/gensupport" in any of:
	/usr/local/go/src/google.golang.org/api/gensupport (from $GOROOT)
	/home/username/go/src/google.golang.org/api/gensupport (from $GOPATH)
```

**Comment by bradfitz** [comment] 2019-09-11 19:33
It was removed in https://github.com/googleapis/google-api-go-client/commit/326e17a21103f4ccf44ac1b40587ce7bcdd58b14

What did it break for you? Were you trying to use gensupport directly? If so, why?

/cc @jadekler @tbpg

**Comment by h8liu** [comment] 2019-09-11 19:42
there are several external usages of gensupport. For example:

cloud.google.com/go/translate/internal/translate/v2
cloud.google.com/go/trace

this move breaks the build of these packages.

These packages actually also comes from google cloud.

**Comment by jadekler** [comment] 2019-09-11 19:51
Thanks - we're aware of the breakage and are working to fix it. HEAD should be fixed, though a few tests are still borked (https://code-review.googlesource.com/c/google-api-go-client/+/45272). Could you try updating and see if it's fixed?

BTW: adopting Go modules would help you avoid this kind of dev churn, since we make sure all our libraries are in a good place before releasing a new version. If you'd like to adopt Go modules, check out https://blog.golang.org/migrating-to-go-modules.

**Comment by jadekler** [comment] 2019-09-11 20:14
Should be fixed now. Please comment back if you see additional problems. We've also fixed (removed) the usages of gensupport in `cloud.google.com/go`.

**Closed by jadekler** 2019-09-11 20:14 UTC
Labels: priority: p1, type: bug

**Comment by d1vi** [comment] 2019-09-11 20:19
Sorry, not working here yet.

I'm now getting
```
Fetching https://cloud.google.com/go/trace?go-get=1
Parsing meta tags from https://cloud.google.com/go/trace?go-get=1 (status code 200)
get "cloud.google.com/go/trace": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at https://cloud.google.com/go/trace?go-get=1
get "cloud.google.com/go/trace": verifying non-authoritative meta tag
Fetching https://cloud.google.com/go?go-get=1
Parsing meta tags from https://cloud.google.com/go?go-get=1 (status code 200)
cloud.google.com/go (download)
package cloud.google.com/go/trace: no Go files in /go/src/cloud.google.com/go/trace
```

**Comment by jadekler** [comment] 2019-09-11 20:24
Ah, we probably have to remove that page. Let me see if I can do so.

**Comment by jadekler** [comment] 2019-09-11 20:24
Hmm... reportedly this shouldn't happen. Are you using Go modules? Are you at HEAD (as of 5m ago)?

**Comment by d1vi** [comment] 2019-09-11 20:39
Yes, I'm on HEAD as of 5m ago, I'm running same working test/build that was OK three hours ago before that breaking change happened on my project on CircleCI, also locally.

I'm not using go modules.

**Comment by jadekler** [comment] 2019-09-11 20:55
I'm unable to replicate this:

```
deklerk at deklerk in ~/workspace/go/src
$ rm -rf *
deklerk at deklerk in ~/workspace/go/src
$ export GO111MODULE=off
deklerk at deklerk in ~/workspace/go/src
$ export GOPATH=~/workspace/go/
deklerk at deklerk in ~/workspace/go/src
$ go get -u cloud.google.com/go/...
deklerk at deklerk in ~/workspace/go/src
$ cd cloud.google.com/go/
deklerk at deklerk in ~/workspace/go/src/cloud.google.com/go on master
$ go build ./...
deklerk at deklerk in ~/workspace/go/src/cloud.google.com/go on master
$ 
```

Could you provide steps to repro?

**Comment by d1vi** [comment] 2019-09-11 21:34
`export GO111MODULE=off`

Did the job.

Some dep might be using go-modules (?) Confirmed solved.

**Comment by jkopczyn** [comment] 2019-10-18 18:56
I see the same bug and the steps you took to repro, reproduce it for me

**Comment by jadekler** [comment] 2019-10-18 19:43
@jkopczyn gensupport has been moved to `internal/`. It was never intended to be relied upon directly (as per its documentation).

**Comment by jkopczyn** [comment] 2019-10-18 20:13
I was not depending on it directly. The move broke compilation of my dependencies.

I followed the steps in #issuecomment-530561997 and they had no effect on the error.

**Comment by jadekler** [comment] 2019-10-18 20:18
Would you mind please filing a new issue with an error log showing?

**Comment by jkopczyn** [comment] 2019-10-18 20:20
It's literally identical to the OP of this issue.

**Comment by jadekler** [comment] 2019-10-18 20:32
Right, but the investigation isn't. Closing this now - please an open a new issue with a log of your error if you are experiencing this problem.
